[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_VERSION = "10.9.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "@netlify/plugin-gatsby"

